Update to pytest 4.5.0
This matches the pytest in the v19 lsst_distrib stack.

Traceback (most recent call last):
  File "pytest", line 8, in <module>
    sys.exit(main())
  File "python3.7/site-packages/_pytest/config/__init__.py", line 61, in main
    config = _prepareconfig(args, plugins)
  File "python3.7/site-packages/_pytest/config/__init__.py", line 182, in _prepareconfig
    config = get_config()
  File "python3.7/site-packages/_pytest/config/__init__.py", line 156, in get_config
    pluginmanager.import_plugin(spec)
  File "python3.7/site-packages/_pytest/config/__init__.py", line 530, in import_plugin
    __import__(importspec)
  File "python3.7/site-packages/_pytest/tmpdir.py", line 25, in <module>
    class TempPathFactory(object):
  File "python3.7/site-packages/_pytest/tmpdir.py", line 35, in TempPathFactory
    lambda p: Path(os.path.abspath(six.text_type(p)))
TypeError: attrib() got an unexpected keyword argument 'convert'