Create new, simpler pipelines config module
The previous configuration system (documenteer.sphinxconfig.stackconf)
suffered from recursion errors during the sphinx build:

  site-packages/sphinx/config.py", line 49, in is_serializable
      if isinstance(obj, UNSERIALIZABLE_TYPES):
  RecursionError: maximum recursion depth exceeded while calling a Python object

This might have been because of the globals injection trick. This new
way of establishing Sphinx configuration is simpler: variables are in
the module namespace, and users simply import the module's contents into
their conf.py file.

I also make an effort to ensure that only variables that need to be in
conf.py are exported from this configuration; imported modules are
deleted for instance, after they are used.

documenteer.conf.pipelines will replace
documenteer.sphinxconfig.stackconf.